$axure.loadCurrentPage({
  "url":"抢购详情页.html",
  "generationDate":new Date(1411537639000),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6cfe7fc6d4d647e280e093e4c8866659",
    "type":"Axure:Page",
    "name":"抢购详情页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e5f83e449ea647cebb07683efc2f2ed7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":24},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9badf8822b03428fb4b30b5c8158ebc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":24},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u12.png"}},
{
          "id":"8b9893035b0c4459a5e86b81fcf2d25b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":0,
              "y":14},
            "size":{
              "width":320,
              "height":496},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c56dc454c24e44ecb0949930729d42d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":14},
                "size":{
                  "width":320,
                  "height":496},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/抢购详情页/u2.png"}},
{
          "id":"0e846aef1b564bf28e6639e1ee8ca397",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF148AF6},
            "location":{
              "x":0,
              "y":23},
            "size":{
              "width":320,
              "height":44},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF148AF6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32542918f0a54b8fb86a0dfee4d53c35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF148AF6},
                "location":{
                  "x":0,
                  "y":23},
                "size":{
                  "width":320,
                  "height":44},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF148AF6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u6.png"}},
{
          "id":"551535fc7c314ec9964d375479ef202f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":103},
            "size":{
              "width":320,
              "height":517},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae62a9d20edf4304b7e69eb20234a421",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":103},
                "size":{
                  "width":320,
                  "height":517},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/抢购详情页/u6.png"}},
{
          "id":"1d9acca44c894570987c61c6208550de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Bold', '华文细黑'",
            "fontSize":"18px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":113,
              "y":30},
            "size":{
              "width":80,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe587529bc6d40378558160bd63a3fa3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Bold', '华文细黑'",
                "fontSize":"18px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":113,
                  "y":30},
                "size":{
                  "width":80,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f3205117bac443abd4d0a93aaf21d37",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":24},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"670431154a9b412c957c2985832b4e41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":24},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u12.png"}},
{
          "id":"d14dc538aea743f589e2fe94827d5273",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":5,
              "y":30},
            "size":{
              "width":80,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a8df2788fd64bb1a3bda64687023322",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":5,
                  "y":30},
                "size":{
                  "width":80,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a00b75b8a1124b6fa565d6e5b2423c88",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":131},
            "size":{
              "width":318,
              "height":121}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"817e158685884a04be700456a223159a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":131},
                "size":{
                  "width":318,
                  "height":121}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动详情（正在进行）/u10.jpg"}},
{
          "id":"c7b3465a1fb442128ce2d6eaa3116e8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":77},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb699ed01ba641ae938a0501181db2fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":77},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aef47adaedee47f2995f5217887da73c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":284},
            "size":{
              "width":296,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4833942152b4c00b63d34c5f77a0a9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":284},
                "size":{
                  "width":296,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"606f6d81ebc4429ea54b57ca277b21bd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":350},
            "size":{
              "width":318,
              "height":121}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44350d7802c34028a7c6ed364edf77d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":350},
                "size":{
                  "width":318,
                  "height":121}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动详情（正在进行）/u10.jpg"}},
{
          "id":"51038f6f40aa4cc683b6ba35c1fa0932",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":485},
            "size":{
              "width":296,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"059e6c3199874af994f3e551255aa635",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":485},
                "size":{
                  "width":296,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e160c1e8471470b867121c0e6c22d37",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":534},
            "size":{
              "width":296,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f7ea42cd47e4c2b94d254f79750eef5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":534},
                "size":{
                  "width":296,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e5f83e449ea647cebb07683efc2f2ed7":{
      "scriptId":"u0"},
    "9badf8822b03428fb4b30b5c8158ebc5":{
      "scriptId":"u1"},
    "8b9893035b0c4459a5e86b81fcf2d25b":{
      "scriptId":"u2"},
    "c56dc454c24e44ecb0949930729d42d9":{
      "scriptId":"u3"},
    "0e846aef1b564bf28e6639e1ee8ca397":{
      "scriptId":"u4"},
    "32542918f0a54b8fb86a0dfee4d53c35":{
      "scriptId":"u5"},
    "551535fc7c314ec9964d375479ef202f":{
      "scriptId":"u6"},
    "ae62a9d20edf4304b7e69eb20234a421":{
      "scriptId":"u7"},
    "1d9acca44c894570987c61c6208550de":{
      "scriptId":"u8"},
    "fe587529bc6d40378558160bd63a3fa3":{
      "scriptId":"u9"},
    "0f3205117bac443abd4d0a93aaf21d37":{
      "scriptId":"u10"},
    "670431154a9b412c957c2985832b4e41":{
      "scriptId":"u11"},
    "d14dc538aea743f589e2fe94827d5273":{
      "scriptId":"u12"},
    "2a8df2788fd64bb1a3bda64687023322":{
      "scriptId":"u13"},
    "a00b75b8a1124b6fa565d6e5b2423c88":{
      "scriptId":"u14"},
    "817e158685884a04be700456a223159a":{
      "scriptId":"u15"},
    "c7b3465a1fb442128ce2d6eaa3116e8d":{
      "scriptId":"u16"},
    "cb699ed01ba641ae938a0501181db2fe":{
      "scriptId":"u17"},
    "aef47adaedee47f2995f5217887da73c":{
      "scriptId":"u18"},
    "b4833942152b4c00b63d34c5f77a0a9b":{
      "scriptId":"u19"},
    "606f6d81ebc4429ea54b57ca277b21bd":{
      "scriptId":"u20"},
    "44350d7802c34028a7c6ed364edf77d3":{
      "scriptId":"u21"},
    "51038f6f40aa4cc683b6ba35c1fa0932":{
      "scriptId":"u22"},
    "059e6c3199874af994f3e551255aa635":{
      "scriptId":"u23"},
    "9e160c1e8471470b867121c0e6c22d37":{
      "scriptId":"u24"},
    "9f7ea42cd47e4c2b94d254f79750eef5":{
      "scriptId":"u25"}}});