$axure.loadCurrentPage({
  "url":"活动详情（即将上线）.html",
  "generationDate":new Date(1411537635000),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"093795ad8e9c4111aa0108350cd0edb3",
    "type":"Axure:Page",
    "name":"活动详情（即将上线）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a8a2fc730a0e4335867fdf2e0f0065bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":0,
              "y":14},
            "size":{
              "width":320,
              "height":1166},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cac8d4fe424844ae807a504ee65302e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":14},
                "size":{
                  "width":320,
                  "height":1166},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u482.png"}},
{
          "id":"67c993d8c0f04bcc96decdbfe83c71dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF148AF6},
            "location":{
              "x":0,
              "y":24},
            "size":{
              "width":320,
              "height":44},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF148AF6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07edb02297304dcaa0de806a318021d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF148AF6},
                "location":{
                  "x":0,
                  "y":24},
                "size":{
                  "width":320,
                  "height":44},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF148AF6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u6.png"}},
{
          "id":"434ff74d5be9440a8dc6303a28fb7f24",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Bold', '华文细黑'",
            "fontSize":"18px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":113,
              "y":30},
            "size":{
              "width":80,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4862be8586604312a98dc3286b22ea67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Bold', '华文细黑'",
                "fontSize":"18px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":113,
                  "y":30},
                "size":{
                  "width":80,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48bcc53dd5864b27aedb3feee1660d84",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":24},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9788644bc0194799a8307338b89277d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":24},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u12.png"}},
{
          "id":"7c007be2d6634e79972ddd374a415da3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":5,
              "y":30},
            "size":{
              "width":80,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"169177d26d4841fa9ffd886c7b019fe6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":5,
                  "y":30},
                "size":{
                  "width":80,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ec98df087854202990994fa5fe6d2cb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":68},
            "size":{
              "width":318,
              "height":121}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b925ef23b7804889ac16b5366de74ab5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":68},
                "size":{
                  "width":318,
                  "height":121}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动详情（正在进行）/u10.jpg"}},
{
          "id":"2c6e8675ec774cd8861122c2aa670f35",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":188},
            "size":{
              "width":320,
              "height":82},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f0f59831dc04808994904aa8b69031f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":188},
                "size":{
                  "width":320,
                  "height":82},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u820.png"}},
{
          "id":"a69a3072bae84dfd805a66811eccdd07",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":210,
              "y":200},
            "size":{
              "width":93,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"736035b62c4f47e782369c9b71dd124a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":210,
                  "y":200},
                "size":{
                  "width":93,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u836.png"}},
{
          "id":"36372d2476e14a1eb52832ca4e8839be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":219,
              "y":242},
            "size":{
              "width":75,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1c02932a4eb4453bd2eebb8fbb42ce4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":219,
                  "y":242},
                "size":{
                  "width":75,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0adff0e7bc04384ab6e0a9f7198db38",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"34px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF39611,
              "opacity":1},
            "location":{
              "x":12,
              "y":194},
            "size":{
              "width":20,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48cfab13473e40119de6942c1f2d130f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"34px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF39611,
                  "opacity":1},
                "location":{
                  "x":12,
                  "y":194},
                "size":{
                  "width":20,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"73e3d2d4648546f08b9592c0368f7ec3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF39611,
              "opacity":1},
            "location":{
              "x":33,
              "y":212},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b666d1428e1b45a487f5ab2c28eb3dcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF39611,
                  "opacity":1},
                "location":{
                  "x":33,
                  "y":212},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a895190c3db048cdbe35aa525f32a25b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":58,
              "y":214},
            "size":{
              "width":89,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddd0dc1cb6384f07ad48ba9d508037a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":58,
                  "y":214},
                "size":{
                  "width":89,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0c7caa08c3740ae9f6ebbfa45993d10",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":16,
              "y":240},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c9e18f922a14e58acd9b2474136764d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":16,
                  "y":240},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"827b8aacfaec4a5ea68a4a0daaedb475",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":302},
            "size":{
              "width":320,
              "height":110},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1310becf1233491f9afe6859fbdcd2e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":302},
                "size":{
                  "width":320,
                  "height":110},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情状态模板/u6.png"}},
{
          "id":"b4887118158d49ab955d9f673bb3f359",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":282},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d71caabead049de9f76739368ba029f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":282},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59cecb448483498abaefc2553632511a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":324},
            "size":{
              "width":296,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82a5c20e93ea42d0b3e1d445af1af373",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":324},
                "size":{
                  "width":296,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86d85e0a108943a2ad09968ebe71a171",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":384},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"923b35d5d73240cbbb8ad13d0036ba8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":384},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76aebed1324a454b820f6462bad61453",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":76,
              "y":386},
            "size":{
              "width":9,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69fe4aa50f0e441ba2975a8531e04d07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":76,
                  "y":386},
                "size":{
                  "width":9,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u354.png"}},
{
          "id":"853886ddb7b645c8ab24e03df81b0906",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":450},
            "size":{
              "width":320,
              "height":184},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2dda653b51946cdb4ee1b5297e12d35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":450},
                "size":{
                  "width":320,
                  "height":184},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情状态模板/u263.png"}},
{
          "id":"17a68bfcafd545c0ae7e3d321ca9db7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":458},
            "size":{
              "width":296,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6c86b77844f4e59ac4295e984a0fbb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":458},
                "size":{
                  "width":296,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0be3cc2750d0451e8985cbe2047a6121",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":494},
            "size":{
              "width":86,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cff8ed0259e64ab0a656dac67a92abe9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":494},
                "size":{
                  "width":86,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u616.png"}},
{
          "id":"aaa743553cb74c5fbbad4857df11c42f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":100,
              "y":498},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"601866c1a6a34b7687977931ec740fb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":100,
                  "y":498},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f61048ddbe9b4a899adc5652dc08897f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"34px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":99,
              "y":540},
            "size":{
              "width":58,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8460c1af8a6b4e82a7c2ca5b0aeb0a5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"34px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":99,
                  "y":540},
                "size":{
                  "width":58,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a2ec37a8c664b458768f6b48614eda2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":159,
              "y":558},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e1e0f3a19f048e2a57d6b00cb7e0b1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":159,
                  "y":558},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"816894f40df047348bb872417af2920a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":14,
              "y":590},
            "size":{
              "width":286,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0e7537769064ce89913b440bab91ba1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":14,
                  "y":590},
                "size":{
                  "width":286,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情状态模板/u303.png"}},
{
          "id":"5c72f1bfe800452586692f11c7737ae3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":184,
              "y":558},
            "size":{
              "width":89,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cec1d8fbe3854e82bf397247d13c2a39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":184,
                  "y":558},
                "size":{
                  "width":89,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d19233024df4ef3a0e4355db0713d01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":430},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fe022d565634a9d91a60a0fd6000ecb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":430},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38cf9c1979354aee9baab5cd2129bcfc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":646},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b3cb6c2170440f8bac00743eb297dec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":11,
                  "y":646},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ab04a97810744ba8da3fc366614bb84",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":524},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c350ffb8c2324bceab46dc70e01037a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":524},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b45267d8c1f8426abacd4e6899cc7e1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":958},
            "size":{
              "width":320,
              "height":212},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac51f88867cf4e56973567429a5586ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":958},
                "size":{
                  "width":320,
                  "height":212},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动详情（正在进行）/u60.png"}},
{
          "id":"c2041bcfd202492e82012d1789514c3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":936},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04469d4ecf7b4bd49acc34fe4bca6c72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":936},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6428d66b3804487aa89375161e0cdfbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":974},
            "size":{
              "width":296,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75f854cdfc52441e90974a794bdf92c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":974},
                "size":{
                  "width":296,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a9a53c41ec914c7696f59f8e2778485f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":1138},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa0ad1c17b9942e0b550ded7fd8c2952",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":1138},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"345550560f28463ca8dc968ae0759723",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":76,
              "y":1140},
            "size":{
              "width":9,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb5cefb29a3f4fa7b0674980154900d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":76,
                  "y":1140},
                "size":{
                  "width":9,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u354.png"}},
{
          "id":"d26b2119a2914514a8fa4c6df61f74ce",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1122},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/活动详情（正在进行）/u70_line.png"}},
{
          "id":"d72a0599c2494f638b165986a365be6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":886},
            "size":{
              "width":320,
              "height":39},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b37804c350d24316aa9d1b617c8c1a1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":886},
                "size":{
                  "width":320,
                  "height":39},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动详情（正在进行）/u83.png"}},
{
          "id":"616658dd264346c59ce71c2518a33401",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":898},
            "size":{
              "width":287,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b0413aeb1db49e684149b235da4d045",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":11,
                  "y":898},
                "size":{
                  "width":287,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08e170a85c98426eb8541f8fd7fe9281",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":275,
              "y":36},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"963502ca33ab4deca64dde3c186757fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":275,
                  "y":36},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c938844c217a4114a05473a30edf7ca4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":668},
            "size":{
              "width":320,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"824b96dcdca14049b199ce98a8a1d188",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":668},
                "size":{
                  "width":320,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情状态模板/u351.png"}},
{
          "id":"8b35757ccd2b4a0a80668493002b1534",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":674},
            "size":{
              "width":59,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5e17abfca9e47b0a64330cb7e30b011",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":11,
                  "y":674},
                "size":{
                  "width":59,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u616.png"}},
{
          "id":"4d34591e2dc34d6c8e44b090c1171d99",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":80,
              "y":684},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60bbf10a11d64cde96a851c026ecae55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":80,
                  "y":684},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f82e356dd8ee43a291dda17b1a26b60d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":740},
            "size":{
              "width":320,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69de8f1be504447188c07f7630fc1c29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":740},
                "size":{
                  "width":320,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情状态模板/u351.png"}},
{
          "id":"cc26da21eac34e9585ec82915de21f2e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":748},
            "size":{
              "width":59,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4ccb4b24797400a84a65601071407cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":11,
                  "y":748},
                "size":{
                  "width":59,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u616.png"}},
{
          "id":"235cb942ba224b94a50c9f54423e3a9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":80,
              "y":756},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4beb6d118b9d4f27bb70623e4cd644aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":80,
                  "y":756},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e8c43d0e2d14ca0a4b9ceb9569b54dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":814},
            "size":{
              "width":320,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d9ec678e35f4073856c372a02630c85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":814},
                "size":{
                  "width":320,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情状态模板/u351.png"}},
{
          "id":"be7cd2487865464cae1ca3165334c66f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":820},
            "size":{
              "width":59,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9a0e5cf809d4edc9a48b53c93102a04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":11,
                  "y":820},
                "size":{
                  "width":59,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u616.png"}},
{
          "id":"0e47fda4716f4ba3a4583b5588a28ca3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":80,
              "y":830},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47b238e8a81448cd88b84dddc97c610f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":80,
                  "y":830},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24c91fb2093840e5b3ee0c072db1660b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":1194},
            "size":{
              "width":177,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a36bad51fc74e3eaefb18ba5bc878df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":66,
                  "y":1194},
                "size":{
                  "width":177,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动详情（秒杀中）/u120.png"}},
{
          "id":"6a642a16a99b4264ae8d3b79db536ab9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xC6000000},
            "location":{
              "x":0,
              "y":450},
            "size":{
              "width":320,
              "height":184},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"093cfc1fe6774d9e8ef1887e2821e0e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xC6000000},
                "location":{
                  "x":0,
                  "y":450},
                "size":{
                  "width":320,
                  "height":184},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情状态模板/u447.png"}},
{
          "id":"ac7f6c3071904901b4473adf1341fcb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":87,
              "y":510},
            "size":{
              "width":143,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7999ad3687c4ea8b0c58bf1df8f9036",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":87,
                  "y":510},
                "size":{
                  "width":143,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cdd42ed14721473eb75e547f9df508bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":704},
            "size":{
              "width":21,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c77ea41230314aec9922a5a9cfbeaf33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":704},
                "size":{
                  "width":21,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10d812adffc242cb970c313160e27058",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":778},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0aed6ce340a4521915a0ede270f90d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":778},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c29e1b2d655f46948cd1d51d96fa6805",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":850},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"510335bfea554cef80be56c81bf8b748",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":850},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0aa8ae43b425449284788e6864db1182",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":756},
            "size":{
              "width":74,
              "height":32},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0d125351cee469e94481b6b15ae47e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":219,
                  "y":756},
                "size":{
                  "width":74,
                  "height":32},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情状态模板/u409.png"}},
{
          "id":"749a08b048074eb9a5f5178a43b2a996",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":688},
            "size":{
              "width":74,
              "height":32},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"798de30987ca438da901c7efa08107f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":219,
                  "y":688},
                "size":{
                  "width":74,
                  "height":32},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情状态模板/u409.png"}},
{
          "id":"420887695b4143849c24fde229e7e8bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":826},
            "size":{
              "width":74,
              "height":32},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc2159a227ad40dab34fb98ecec30713",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":219,
                  "y":826},
                "size":{
                  "width":74,
                  "height":32},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情状态模板/u409.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "a8a2fc730a0e4335867fdf2e0f0065bb":{
      "scriptId":"u0"},
    "cac8d4fe424844ae807a504ee65302e5":{
      "scriptId":"u1"},
    "67c993d8c0f04bcc96decdbfe83c71dd":{
      "scriptId":"u2"},
    "07edb02297304dcaa0de806a318021d2":{
      "scriptId":"u3"},
    "434ff74d5be9440a8dc6303a28fb7f24":{
      "scriptId":"u4"},
    "4862be8586604312a98dc3286b22ea67":{
      "scriptId":"u5"},
    "48bcc53dd5864b27aedb3feee1660d84":{
      "scriptId":"u6"},
    "9788644bc0194799a8307338b89277d1":{
      "scriptId":"u7"},
    "7c007be2d6634e79972ddd374a415da3":{
      "scriptId":"u8"},
    "169177d26d4841fa9ffd886c7b019fe6":{
      "scriptId":"u9"},
    "3ec98df087854202990994fa5fe6d2cb":{
      "scriptId":"u10"},
    "b925ef23b7804889ac16b5366de74ab5":{
      "scriptId":"u11"},
    "2c6e8675ec774cd8861122c2aa670f35":{
      "scriptId":"u12"},
    "0f0f59831dc04808994904aa8b69031f":{
      "scriptId":"u13"},
    "a69a3072bae84dfd805a66811eccdd07":{
      "scriptId":"u14"},
    "736035b62c4f47e782369c9b71dd124a":{
      "scriptId":"u15"},
    "36372d2476e14a1eb52832ca4e8839be":{
      "scriptId":"u16"},
    "b1c02932a4eb4453bd2eebb8fbb42ce4":{
      "scriptId":"u17"},
    "c0adff0e7bc04384ab6e0a9f7198db38":{
      "scriptId":"u18"},
    "48cfab13473e40119de6942c1f2d130f":{
      "scriptId":"u19"},
    "73e3d2d4648546f08b9592c0368f7ec3":{
      "scriptId":"u20"},
    "b666d1428e1b45a487f5ab2c28eb3dcd":{
      "scriptId":"u21"},
    "a895190c3db048cdbe35aa525f32a25b":{
      "scriptId":"u22"},
    "ddd0dc1cb6384f07ad48ba9d508037a1":{
      "scriptId":"u23"},
    "f0c7caa08c3740ae9f6ebbfa45993d10":{
      "scriptId":"u24"},
    "9c9e18f922a14e58acd9b2474136764d":{
      "scriptId":"u25"},
    "827b8aacfaec4a5ea68a4a0daaedb475":{
      "scriptId":"u26"},
    "1310becf1233491f9afe6859fbdcd2e3":{
      "scriptId":"u27"},
    "b4887118158d49ab955d9f673bb3f359":{
      "scriptId":"u28"},
    "8d71caabead049de9f76739368ba029f":{
      "scriptId":"u29"},
    "59cecb448483498abaefc2553632511a":{
      "scriptId":"u30"},
    "82a5c20e93ea42d0b3e1d445af1af373":{
      "scriptId":"u31"},
    "86d85e0a108943a2ad09968ebe71a171":{
      "scriptId":"u32"},
    "923b35d5d73240cbbb8ad13d0036ba8e":{
      "scriptId":"u33"},
    "76aebed1324a454b820f6462bad61453":{
      "scriptId":"u34"},
    "69fe4aa50f0e441ba2975a8531e04d07":{
      "scriptId":"u35"},
    "853886ddb7b645c8ab24e03df81b0906":{
      "scriptId":"u36"},
    "c2dda653b51946cdb4ee1b5297e12d35":{
      "scriptId":"u37"},
    "17a68bfcafd545c0ae7e3d321ca9db7a":{
      "scriptId":"u38"},
    "b6c86b77844f4e59ac4295e984a0fbb1":{
      "scriptId":"u39"},
    "0be3cc2750d0451e8985cbe2047a6121":{
      "scriptId":"u40"},
    "cff8ed0259e64ab0a656dac67a92abe9":{
      "scriptId":"u41"},
    "aaa743553cb74c5fbbad4857df11c42f":{
      "scriptId":"u42"},
    "601866c1a6a34b7687977931ec740fb9":{
      "scriptId":"u43"},
    "f61048ddbe9b4a899adc5652dc08897f":{
      "scriptId":"u44"},
    "8460c1af8a6b4e82a7c2ca5b0aeb0a5e":{
      "scriptId":"u45"},
    "2a2ec37a8c664b458768f6b48614eda2":{
      "scriptId":"u46"},
    "4e1e0f3a19f048e2a57d6b00cb7e0b1a":{
      "scriptId":"u47"},
    "816894f40df047348bb872417af2920a":{
      "scriptId":"u48"},
    "f0e7537769064ce89913b440bab91ba1":{
      "scriptId":"u49"},
    "5c72f1bfe800452586692f11c7737ae3":{
      "scriptId":"u50"},
    "cec1d8fbe3854e82bf397247d13c2a39":{
      "scriptId":"u51"},
    "3d19233024df4ef3a0e4355db0713d01":{
      "scriptId":"u52"},
    "1fe022d565634a9d91a60a0fd6000ecb":{
      "scriptId":"u53"},
    "38cf9c1979354aee9baab5cd2129bcfc":{
      "scriptId":"u54"},
    "5b3cb6c2170440f8bac00743eb297dec":{
      "scriptId":"u55"},
    "9ab04a97810744ba8da3fc366614bb84":{
      "scriptId":"u56"},
    "c350ffb8c2324bceab46dc70e01037a7":{
      "scriptId":"u57"},
    "b45267d8c1f8426abacd4e6899cc7e1b":{
      "scriptId":"u58"},
    "ac51f88867cf4e56973567429a5586ed":{
      "scriptId":"u59"},
    "c2041bcfd202492e82012d1789514c3c":{
      "scriptId":"u60"},
    "04469d4ecf7b4bd49acc34fe4bca6c72":{
      "scriptId":"u61"},
    "6428d66b3804487aa89375161e0cdfbe":{
      "scriptId":"u62"},
    "75f854cdfc52441e90974a794bdf92c4":{
      "scriptId":"u63"},
    "a9a53c41ec914c7696f59f8e2778485f":{
      "scriptId":"u64"},
    "fa0ad1c17b9942e0b550ded7fd8c2952":{
      "scriptId":"u65"},
    "345550560f28463ca8dc968ae0759723":{
      "scriptId":"u66"},
    "cb5cefb29a3f4fa7b0674980154900d3":{
      "scriptId":"u67"},
    "d26b2119a2914514a8fa4c6df61f74ce":{
      "scriptId":"u68"},
    "d72a0599c2494f638b165986a365be6c":{
      "scriptId":"u69"},
    "b37804c350d24316aa9d1b617c8c1a1a":{
      "scriptId":"u70"},
    "616658dd264346c59ce71c2518a33401":{
      "scriptId":"u71"},
    "5b0413aeb1db49e684149b235da4d045":{
      "scriptId":"u72"},
    "08e170a85c98426eb8541f8fd7fe9281":{
      "scriptId":"u73"},
    "963502ca33ab4deca64dde3c186757fc":{
      "scriptId":"u74"},
    "c938844c217a4114a05473a30edf7ca4":{
      "scriptId":"u75"},
    "824b96dcdca14049b199ce98a8a1d188":{
      "scriptId":"u76"},
    "8b35757ccd2b4a0a80668493002b1534":{
      "scriptId":"u77"},
    "f5e17abfca9e47b0a64330cb7e30b011":{
      "scriptId":"u78"},
    "4d34591e2dc34d6c8e44b090c1171d99":{
      "scriptId":"u79"},
    "60bbf10a11d64cde96a851c026ecae55":{
      "scriptId":"u80"},
    "f82e356dd8ee43a291dda17b1a26b60d":{
      "scriptId":"u81"},
    "69de8f1be504447188c07f7630fc1c29":{
      "scriptId":"u82"},
    "cc26da21eac34e9585ec82915de21f2e":{
      "scriptId":"u83"},
    "e4ccb4b24797400a84a65601071407cf":{
      "scriptId":"u84"},
    "235cb942ba224b94a50c9f54423e3a9a":{
      "scriptId":"u85"},
    "4beb6d118b9d4f27bb70623e4cd644aa":{
      "scriptId":"u86"},
    "2e8c43d0e2d14ca0a4b9ceb9569b54dd":{
      "scriptId":"u87"},
    "7d9ec678e35f4073856c372a02630c85":{
      "scriptId":"u88"},
    "be7cd2487865464cae1ca3165334c66f":{
      "scriptId":"u89"},
    "d9a0e5cf809d4edc9a48b53c93102a04":{
      "scriptId":"u90"},
    "0e47fda4716f4ba3a4583b5588a28ca3":{
      "scriptId":"u91"},
    "47b238e8a81448cd88b84dddc97c610f":{
      "scriptId":"u92"},
    "24c91fb2093840e5b3ee0c072db1660b":{
      "scriptId":"u93"},
    "6a36bad51fc74e3eaefb18ba5bc878df":{
      "scriptId":"u94"},
    "6a642a16a99b4264ae8d3b79db536ab9":{
      "scriptId":"u95"},
    "093cfc1fe6774d9e8ef1887e2821e0e3":{
      "scriptId":"u96"},
    "ac7f6c3071904901b4473adf1341fcb6":{
      "scriptId":"u97"},
    "a7999ad3687c4ea8b0c58bf1df8f9036":{
      "scriptId":"u98"},
    "cdd42ed14721473eb75e547f9df508bd":{
      "scriptId":"u99"},
    "c77ea41230314aec9922a5a9cfbeaf33":{
      "scriptId":"u100"},
    "10d812adffc242cb970c313160e27058":{
      "scriptId":"u101"},
    "b0aed6ce340a4521915a0ede270f90d2":{
      "scriptId":"u102"},
    "c29e1b2d655f46948cd1d51d96fa6805":{
      "scriptId":"u103"},
    "510335bfea554cef80be56c81bf8b748":{
      "scriptId":"u104"},
    "0aa8ae43b425449284788e6864db1182":{
      "scriptId":"u105"},
    "b0d125351cee469e94481b6b15ae47e0":{
      "scriptId":"u106"},
    "749a08b048074eb9a5f5178a43b2a996":{
      "scriptId":"u107"},
    "798de30987ca438da901c7efa08107f7":{
      "scriptId":"u108"},
    "420887695b4143849c24fde229e7e8bc":{
      "scriptId":"u109"},
    "fc2159a227ad40dab34fb98ecec30713":{
      "scriptId":"u110"}}});