$axure.loadCurrentPage({
  "url":"幸运机会.html",
  "generationDate":new Date(1411537637453.13),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"39764068ed464830a8e721071b66ffdf",
    "type":"Axure:Page",
    "name":"幸运机会",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b5952b30fc8a41fb915bdbbe4d40b939",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":0,
              "y":14},
            "size":{
              "width":320,
              "height":486},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cad8a176871d4337b2ef66ebfda707e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":14},
                "size":{
                  "width":320,
                  "height":486},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/幸运机会/u0.png"}},
{
          "id":"9e236b77b0d84ae6834820f429b5b712",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF148AF6},
            "location":{
              "x":0,
              "y":23},
            "size":{
              "width":320,
              "height":44},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF148AF6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55fba0d8be1540e381df9af236fff4a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF148AF6},
                "location":{
                  "x":0,
                  "y":23},
                "size":{
                  "width":320,
                  "height":44},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF148AF6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u6.png"}},
{
          "id":"0aa8d2e4078a468a8ead79aef1f8e368",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":67},
            "size":{
              "width":320,
              "height":53},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10e8b95c8b5940fa9508040c98e4b2da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":67},
                "size":{
                  "width":320,
                  "height":53},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/幸运机会/u4.png"}},
{
          "id":"06b4f0278f4a478da1ff6be3103e4158",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Bold', '华文细黑'",
            "fontSize":"18px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":113,
              "y":30},
            "size":{
              "width":80,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2980ef670f334bad82de59a1813038c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Bold', '华文细黑'",
                "fontSize":"18px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":113,
                  "y":30},
                "size":{
                  "width":80,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8cc1210ff2df4eb6a16f73f28dac3b35",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":24},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b594cbaafb3b4ce892f541c700b3f99b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":24},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u12.png"}},
{
          "id":"bc5b350a46464a0da7095cca3e0f06db",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":5,
              "y":30},
            "size":{
              "width":80,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0d8b736adfa412086beb29fd2ba6d03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":5,
                  "y":30},
                "size":{
                  "width":80,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"019dac7c9f4346868a2a014f03fc73e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":21,
              "y":87},
            "size":{
              "width":112,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1161216434294572a1640bb615bfa21b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":21,
                  "y":87},
                "size":{
                  "width":112,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"592e20c362b9486d8c2d8ea89f5fff7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":235,
              "y":37},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f64f57b687834a879128c409dfbc2217",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":235,
                  "y":37},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64106517ba554a4ca8d772c259cc9739",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":100,
              "y":134},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bde8d1a8cc8f4968bd484493350ccd44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":100,
                  "y":134},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c4d732aa6ab42bb8044075d03e4e3d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":270,
              "y":134},
            "size":{
              "width":17,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f14cdee161a44bba5809cdca4cb4d99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":270,
                  "y":134},
                "size":{
                  "width":17,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"953e9b7552e4442fa2d14e93eac860c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":100,
              "y":158},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aef0bd34ee964da595e97dde796cbe75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":100,
                  "y":158},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd8e3e8bb14144b3ac1af276c4b89566",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":100,
              "y":184},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5e7c5c51be2457a9cca9f5d4790504f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":100,
                  "y":184},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"55633a209d41413aaa6e41a985791d27",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":100,
              "y":212},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0069b763971d417ca6a59cd4bdc17301",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":100,
                  "y":212},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66d3cc91e806407fa1511603344368b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":270,
              "y":158},
            "size":{
              "width":17,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef909dde609942acaef7fc9212f4545b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":270,
                  "y":158},
                "size":{
                  "width":17,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59a5fe7759bc4e7ab1b50846e04fc38d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":270,
              "y":184},
            "size":{
              "width":17,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ee28216acfd42c087f58fc09385129f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":270,
                  "y":184},
                "size":{
                  "width":17,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c0d8f83f49b4c10bf873d41c99d9cb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":270,
              "y":212},
            "size":{
              "width":17,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ef4fb297bc246e89291325d7af5aa5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":270,
                  "y":212},
                "size":{
                  "width":17,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ee92df9540a44558229c800dcfecb5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":16,
              "y":134},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c73813cad534bd391386ea021205f5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":16,
                  "y":134},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7f9dd74c97f48c0ac4501f5faa87676",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":16,
              "y":160},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d61124f0e3349c2bbff64051a3dcc53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":16,
                  "y":160},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f24b947490cb40a7ab64542788ef7361",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":16,
              "y":186},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f087172b75284a448924d491d7f264c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":16,
                  "y":186},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0aece050cb645c29655bd81fdc5048a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":16,
              "y":212},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fbe3bfa1e514668a97319f5866c24b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":16,
                  "y":212},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5778a2dbd8294f0d9b5269cf1ee04256",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":100,
              "y":262},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45d9910080234aa389573ce8636274bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":100,
                  "y":262},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7500aeab28fe46f187ad8c31dc60bbd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":272,
              "y":262},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"200798995a844f9297b41346711b2592",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":272,
                  "y":262},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21b4f614f683403faaf63cf0df92eb28",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":16,
              "y":262},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"375f6c729e614395bc3038b558700bf1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":16,
                  "y":262},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"caad809ba66c40be9072c4a1a755d85e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":150},
            "size":{
              "width":304,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/幸运机会/u46_line.png"}},
{
          "id":"922ca41175e849c292fa575a21db5f88",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":172},
            "size":{
              "width":304,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/幸运机会/u46_line.png"}},
{
          "id":"37597e1d86094446ac13c7e820e25182",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":204},
            "size":{
              "width":304,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/幸运机会/u46_line.png"}},
{
          "id":"c6701bc71b7c44d9b289b1d5473caef0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":226},
            "size":{
              "width":304,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/幸运机会/u46_line.png"}},
{
          "id":"acc708ab1d8b4d81bd36a446f99d58c5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":254},
            "size":{
              "width":304,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/幸运机会/u46_line.png"}},
{
          "id":"9cc2d4b50e874f70875f80567e46e105",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":276},
            "size":{
              "width":304,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/幸运机会/u46_line.png"}},
{
          "id":"a97a80986a07416b95a1eec523bad5e9",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":134},
            "size":{
              "width":10,
              "height":143},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/幸运机会/u52_line.png"}},
{
          "id":"6e1fe6b0c4de48c9a34eaa5f796bc739",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":214,
              "y":134},
            "size":{
              "width":10,
              "height":143},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/幸运机会/u52_line.png"}},
{
          "id":"386641a0feb44df6aecfc2205586de71",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":120},
            "size":{
              "width":304,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/幸运机会/u46_line.png"}},
{
          "id":"d40bc5e67619491f9e44ee738224062e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":100,
              "y":236},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a001f48d322c468a929e53c9c6f0d601",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":100,
                  "y":236},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3fc8c05e4ead4215b3a59065e036650d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":272,
              "y":236},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c72072f316aa471586225d168a5f8c69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":272,
                  "y":236},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed9e2f398b4d4ad18c771b6918f40c43",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":16,
              "y":236},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d68dc1009254b7c89f4c0608116f931",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":16,
                  "y":236},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57314aabfada44ee952fac328e68404b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":80},
            "size":{
              "width":100,
              "height":31},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24c6cea90a5b47929a7236850183c8d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":80},
                "size":{
                  "width":100,
                  "height":31},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/幸运机会/u61.png"}},
{
          "id":"8c3ed242f491402c847fc7599544a260",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":535},
            "size":{
              "width":284,
              "height":185},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cae6ad43268b467ebf273a3ee4baa822",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":535},
                "size":{
                  "width":284,
                  "height":185},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/幸运机会/u63.png"}},
{
          "id":"dfe6d4924e814a8898499fdb92e75f7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":29,
              "y":615},
            "size":{
              "width":267,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"948e4f8b54a54b79aea6ca41d89b6fa3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":29,
                  "y":615},
                "size":{
                  "width":267,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/幸运机会/u65.png"}},
{
          "id":"6dda43363aa34ec09fadebe1e5e9293c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":45,
              "y":629},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa7898b392714dc68fbdc343b98f29a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":45,
                  "y":629},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f861cd8a56d44e07a54a71ed67f079ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":29,
              "y":589},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed10f9c6d67f4d1ca1f33660ba3a2281",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":29,
                  "y":589},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac79152a1c1845a18ee8c1ef19392900",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":106,
              "y":545},
            "size":{
              "width":121,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3d5d18d6aad4b3bb5a2be558f179053",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":106,
                  "y":545},
                "size":{
                  "width":121,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0104b5fec7ee4b2e863b856f9221f932",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":671},
            "size":{
              "width":10,
              "height":46},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/幸运机会/u73_line.png"}},
{
          "id":"905b0a078e0e459b8cb60ab7e98e4356",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":665},
            "size":{
              "width":280,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/幸运机会/u74_line.png"}},
{
          "id":"997659c6857045e491e6e38406c3d6a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":210,
              "y":687},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a075e66fd00547688b50d40db899d860",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":210,
                  "y":687},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7bafee675ced4c69a0a0e61d5ce2d5b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":70,
              "y":687},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"216b317f9a0540dc869eda4353beb1e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":70,
                  "y":687},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a953701713443868f3367965f2e78f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":420,
              "y":0},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2592ec58629a45f39d55d1fd1b587564",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":420,
                  "y":0},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/幸运机会/u79.png"}},
{
          "id":"62f9643916f84eec9c7d012ea8e53324",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF148AF6},
            "location":{
              "x":420,
              "y":22},
            "size":{
              "width":320,
              "height":44},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF148AF6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78fbb6bc5fd740b6805e53b61537a952",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF148AF6},
                "location":{
                  "x":420,
                  "y":22},
                "size":{
                  "width":320,
                  "height":44},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF148AF6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u6.png"}},
{
          "id":"bc84adb452064e4c8b62d06e31ff319a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Bold', '华文细黑'",
            "fontSize":"18px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":532,
              "y":30},
            "size":{
              "width":80,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa8d301693724b57bcbe93d73e580f41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Bold', '华文细黑'",
                "fontSize":"18px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":532,
                  "y":30},
                "size":{
                  "width":80,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"996545beab9741ccbd5537b0338a2283",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":0},
            "size":{
              "width":320,
              "height":24},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b675af7511a84e5996d03997971e03b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":0},
                "size":{
                  "width":320,
                  "height":24},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u12.png"}},
{
          "id":"21038c4493b14574add1df76c28ee35f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Bold', '华文细黑'",
            "fontSize":"15px",
            "fontWeight":"bold",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":430,
              "y":30},
            "size":{
              "width":80,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a139948b9ec94b018eae3a10a0eff9bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Bold', '华文细黑'",
                "fontSize":"15px",
                "fontWeight":"bold",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":430,
                  "y":30},
                "size":{
                  "width":80,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a235a333d4a24a5f987cca4ae89e350e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":111},
            "size":{
              "width":320,
              "height":167}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46833d7ab5684023b09d488e23a2c0ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":111},
                "size":{
                  "width":320,
                  "height":167}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/幸运机会/u89.png"}},
{
          "id":"c318570414c44267b9f6d67cd18d8e8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":439,
              "y":80},
            "size":{
              "width":282,
              "height":330}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"425345c7c0744c9899ff23f6d087b4c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":439,
                  "y":80},
                "size":{
                  "width":282,
                  "height":330}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa2f2cb2cc574302ad10eda7581c30f3",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e164a2f6dae54fbb9901b309164fec5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}]},
{
          "id":"a4513375f0524b0589b86ff0d56427e0",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"321fbe291d3647a6bd21339cdead7d34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "b5952b30fc8a41fb915bdbbe4d40b939":{
      "scriptId":"u0"},
    "cad8a176871d4337b2ef66ebfda707e3":{
      "scriptId":"u1"},
    "9e236b77b0d84ae6834820f429b5b712":{
      "scriptId":"u2"},
    "55fba0d8be1540e381df9af236fff4a1":{
      "scriptId":"u3"},
    "0aa8d2e4078a468a8ead79aef1f8e368":{
      "scriptId":"u4"},
    "10e8b95c8b5940fa9508040c98e4b2da":{
      "scriptId":"u5"},
    "06b4f0278f4a478da1ff6be3103e4158":{
      "scriptId":"u6"},
    "2980ef670f334bad82de59a1813038c8":{
      "scriptId":"u7"},
    "8cc1210ff2df4eb6a16f73f28dac3b35":{
      "scriptId":"u8"},
    "b594cbaafb3b4ce892f541c700b3f99b":{
      "scriptId":"u9"},
    "bc5b350a46464a0da7095cca3e0f06db":{
      "scriptId":"u10"},
    "a0d8b736adfa412086beb29fd2ba6d03":{
      "scriptId":"u11"},
    "019dac7c9f4346868a2a014f03fc73e9":{
      "scriptId":"u12"},
    "1161216434294572a1640bb615bfa21b":{
      "scriptId":"u13"},
    "592e20c362b9486d8c2d8ea89f5fff7a":{
      "scriptId":"u14"},
    "f64f57b687834a879128c409dfbc2217":{
      "scriptId":"u15"},
    "64106517ba554a4ca8d772c259cc9739":{
      "scriptId":"u16"},
    "bde8d1a8cc8f4968bd484493350ccd44":{
      "scriptId":"u17"},
    "0c4d732aa6ab42bb8044075d03e4e3d8":{
      "scriptId":"u18"},
    "5f14cdee161a44bba5809cdca4cb4d99":{
      "scriptId":"u19"},
    "953e9b7552e4442fa2d14e93eac860c1":{
      "scriptId":"u20"},
    "aef0bd34ee964da595e97dde796cbe75":{
      "scriptId":"u21"},
    "cd8e3e8bb14144b3ac1af276c4b89566":{
      "scriptId":"u22"},
    "e5e7c5c51be2457a9cca9f5d4790504f":{
      "scriptId":"u23"},
    "55633a209d41413aaa6e41a985791d27":{
      "scriptId":"u24"},
    "0069b763971d417ca6a59cd4bdc17301":{
      "scriptId":"u25"},
    "66d3cc91e806407fa1511603344368b2":{
      "scriptId":"u26"},
    "ef909dde609942acaef7fc9212f4545b":{
      "scriptId":"u27"},
    "59a5fe7759bc4e7ab1b50846e04fc38d":{
      "scriptId":"u28"},
    "3ee28216acfd42c087f58fc09385129f":{
      "scriptId":"u29"},
    "4c0d8f83f49b4c10bf873d41c99d9cb9":{
      "scriptId":"u30"},
    "0ef4fb297bc246e89291325d7af5aa5d":{
      "scriptId":"u31"},
    "1ee92df9540a44558229c800dcfecb5c":{
      "scriptId":"u32"},
    "2c73813cad534bd391386ea021205f5a":{
      "scriptId":"u33"},
    "e7f9dd74c97f48c0ac4501f5faa87676":{
      "scriptId":"u34"},
    "2d61124f0e3349c2bbff64051a3dcc53":{
      "scriptId":"u35"},
    "f24b947490cb40a7ab64542788ef7361":{
      "scriptId":"u36"},
    "f087172b75284a448924d491d7f264c4":{
      "scriptId":"u37"},
    "c0aece050cb645c29655bd81fdc5048a":{
      "scriptId":"u38"},
    "7fbe3bfa1e514668a97319f5866c24b6":{
      "scriptId":"u39"},
    "5778a2dbd8294f0d9b5269cf1ee04256":{
      "scriptId":"u40"},
    "45d9910080234aa389573ce8636274bc":{
      "scriptId":"u41"},
    "7500aeab28fe46f187ad8c31dc60bbd8":{
      "scriptId":"u42"},
    "200798995a844f9297b41346711b2592":{
      "scriptId":"u43"},
    "21b4f614f683403faaf63cf0df92eb28":{
      "scriptId":"u44"},
    "375f6c729e614395bc3038b558700bf1":{
      "scriptId":"u45"},
    "caad809ba66c40be9072c4a1a755d85e":{
      "scriptId":"u46"},
    "922ca41175e849c292fa575a21db5f88":{
      "scriptId":"u47"},
    "37597e1d86094446ac13c7e820e25182":{
      "scriptId":"u48"},
    "c6701bc71b7c44d9b289b1d5473caef0":{
      "scriptId":"u49"},
    "acc708ab1d8b4d81bd36a446f99d58c5":{
      "scriptId":"u50"},
    "9cc2d4b50e874f70875f80567e46e105":{
      "scriptId":"u51"},
    "a97a80986a07416b95a1eec523bad5e9":{
      "scriptId":"u52"},
    "6e1fe6b0c4de48c9a34eaa5f796bc739":{
      "scriptId":"u53"},
    "386641a0feb44df6aecfc2205586de71":{
      "scriptId":"u54"},
    "d40bc5e67619491f9e44ee738224062e":{
      "scriptId":"u55"},
    "a001f48d322c468a929e53c9c6f0d601":{
      "scriptId":"u56"},
    "3fc8c05e4ead4215b3a59065e036650d":{
      "scriptId":"u57"},
    "c72072f316aa471586225d168a5f8c69":{
      "scriptId":"u58"},
    "ed9e2f398b4d4ad18c771b6918f40c43":{
      "scriptId":"u59"},
    "8d68dc1009254b7c89f4c0608116f931":{
      "scriptId":"u60"},
    "57314aabfada44ee952fac328e68404b":{
      "scriptId":"u61"},
    "24c6cea90a5b47929a7236850183c8d0":{
      "scriptId":"u62"},
    "8c3ed242f491402c847fc7599544a260":{
      "scriptId":"u63"},
    "cae6ad43268b467ebf273a3ee4baa822":{
      "scriptId":"u64"},
    "dfe6d4924e814a8898499fdb92e75f7f":{
      "scriptId":"u65"},
    "948e4f8b54a54b79aea6ca41d89b6fa3":{
      "scriptId":"u66"},
    "6dda43363aa34ec09fadebe1e5e9293c":{
      "scriptId":"u67"},
    "aa7898b392714dc68fbdc343b98f29a0":{
      "scriptId":"u68"},
    "f861cd8a56d44e07a54a71ed67f079ab":{
      "scriptId":"u69"},
    "ed10f9c6d67f4d1ca1f33660ba3a2281":{
      "scriptId":"u70"},
    "ac79152a1c1845a18ee8c1ef19392900":{
      "scriptId":"u71"},
    "e3d5d18d6aad4b3bb5a2be558f179053":{
      "scriptId":"u72"},
    "0104b5fec7ee4b2e863b856f9221f932":{
      "scriptId":"u73"},
    "905b0a078e0e459b8cb60ab7e98e4356":{
      "scriptId":"u74"},
    "997659c6857045e491e6e38406c3d6a5":{
      "scriptId":"u75"},
    "a075e66fd00547688b50d40db899d860":{
      "scriptId":"u76"},
    "7bafee675ced4c69a0a0e61d5ce2d5b1":{
      "scriptId":"u77"},
    "216b317f9a0540dc869eda4353beb1e5":{
      "scriptId":"u78"},
    "7a953701713443868f3367965f2e78f1":{
      "scriptId":"u79"},
    "2592ec58629a45f39d55d1fd1b587564":{
      "scriptId":"u80"},
    "62f9643916f84eec9c7d012ea8e53324":{
      "scriptId":"u81"},
    "78fbb6bc5fd740b6805e53b61537a952":{
      "scriptId":"u82"},
    "bc84adb452064e4c8b62d06e31ff319a":{
      "scriptId":"u83"},
    "fa8d301693724b57bcbe93d73e580f41":{
      "scriptId":"u84"},
    "996545beab9741ccbd5537b0338a2283":{
      "scriptId":"u85"},
    "b675af7511a84e5996d03997971e03b3":{
      "scriptId":"u86"},
    "21038c4493b14574add1df76c28ee35f":{
      "scriptId":"u87"},
    "a139948b9ec94b018eae3a10a0eff9bc":{
      "scriptId":"u88"},
    "a235a333d4a24a5f987cca4ae89e350e":{
      "scriptId":"u89"},
    "46833d7ab5684023b09d488e23a2c0ad":{
      "scriptId":"u90"},
    "c318570414c44267b9f6d67cd18d8e8a":{
      "scriptId":"u91"},
    "425345c7c0744c9899ff23f6d087b4c4":{
      "scriptId":"u92"},
    "aa2f2cb2cc574302ad10eda7581c30f3":{
      "scriptId":"u93"},
    "e164a2f6dae54fbb9901b309164fec5c":{
      "scriptId":"u94"},
    "a4513375f0524b0589b86ff0d56427e0":{
      "scriptId":"u95"},
    "321fbe291d3647a6bd21339cdead7d34":{
      "scriptId":"u96"}}});