$axure.loadCurrentPage({
  "url":"活动详情（待开奖）.html",
  "generationDate":new Date(1411537634671.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ec889c09bc44456b8ae723c26373df71",
    "type":"Axure:Page",
    "name":"活动详情（待开奖）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a8696e87bdc947a584e48d21c584a197",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":30,
              "y":14},
            "size":{
              "width":320,
              "height":1166},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1c034539db647bd902cfcbef7cfc8fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":30,
                  "y":14},
                "size":{
                  "width":320,
                  "height":1166},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u482.png"}},
{
          "id":"b9089fb4ea5d469bb79055ffe6268eb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF148AF6},
            "location":{
              "x":30,
              "y":24},
            "size":{
              "width":320,
              "height":44},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF148AF6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"958657b42e894746bb1f2fe2eb64a9ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF148AF6},
                "location":{
                  "x":30,
                  "y":24},
                "size":{
                  "width":320,
                  "height":44},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF148AF6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u6.png"}},
{
          "id":"c0f47a67dc7649db95384bd645ae6044",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Bold', '华文细黑'",
            "fontSize":"18px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":143,
              "y":30},
            "size":{
              "width":80,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3943574302e4434180243242e16c6665",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Bold', '华文细黑'",
                "fontSize":"18px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":143,
                  "y":30},
                "size":{
                  "width":80,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8fe9ed1bdc3c4aa49f36fbaebcfb5200",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":0},
            "size":{
              "width":320,
              "height":24},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39c03a5d33c04cda98accd89a96fa3f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":0},
                "size":{
                  "width":320,
                  "height":24},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u12.png"}},
{
          "id":"3714e784c72341acb7599107e0e32cf0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":35,
              "y":30},
            "size":{
              "width":80,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dc818cf78ea4158a59c2e14626ff3cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":35,
                  "y":30},
                "size":{
                  "width":80,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e87bb45e524b4e8da00ce293e4ac90cc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":68},
            "size":{
              "width":318,
              "height":121}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcbb085de4be49e1b2b749d09560db90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":68},
                "size":{
                  "width":318,
                  "height":121}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动详情（正在进行）/u10.jpg"}},
{
          "id":"c7265aff1e804c40989c507958065331",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":188},
            "size":{
              "width":320,
              "height":82},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4e65dd3751e499e93b398e1a0364bfa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":188},
                "size":{
                  "width":320,
                  "height":82},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u820.png"}},
{
          "id":"d2201b73fd844ff69fd5e6824b601a6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":240,
              "y":200},
            "size":{
              "width":93,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f29d6c3588e41bcbe90c03630de4969",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":240,
                  "y":200},
                "size":{
                  "width":93,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u836.png"}},
{
          "id":"eccf1ef4c37149d5bf9f871ed8915708",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":249,
              "y":242},
            "size":{
              "width":75,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"371daa7decbc4bf0935db392206dc726",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":249,
                  "y":242},
                "size":{
                  "width":75,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e32aa35455b7475297d8bfc13ad85e59",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"34px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF39611,
              "opacity":1},
            "location":{
              "x":42,
              "y":194},
            "size":{
              "width":20,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"039ea7124b7442989a62e62ff1030c47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"34px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF39611,
                  "opacity":1},
                "location":{
                  "x":42,
                  "y":194},
                "size":{
                  "width":20,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6667ca28974413c9f6a4f0c7eaedbba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF39611,
              "opacity":1},
            "location":{
              "x":63,
              "y":212},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ec02e3f998346bfaf4dfd3fde8d0387",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF39611,
                  "opacity":1},
                "location":{
                  "x":63,
                  "y":212},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70bfbba32f2d4ed3a7e730d84c55dec9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":88,
              "y":214},
            "size":{
              "width":89,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd13d6276f7746e9887e60cb3905c0ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":88,
                  "y":214},
                "size":{
                  "width":89,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a17238069ffe4dc08a6e3e817483cdf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":46,
              "y":244},
            "size":{
              "width":154,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63a97e890d844aaf80e1afd4796c7fbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":46,
                  "y":244},
                "size":{
                  "width":154,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"183b7c5825f14f1db3f9bd603c2f41b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":450},
            "size":{
              "width":320,
              "height":184},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4c7904d57c34a0cb61f7a3dffc2be2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":450},
                "size":{
                  "width":320,
                  "height":184},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情状态模板/u263.png"}},
{
          "id":"b78ba9087e1c43c081c11b6eb0586945",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":458},
            "size":{
              "width":296,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfaa9d1275804b458a8916775b697778",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":458},
                "size":{
                  "width":296,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46a59231893e4f88b5ce341dd83500ae",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":494},
            "size":{
              "width":86,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23b8733764f54904a3935e3f602068d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":494},
                "size":{
                  "width":86,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u616.png"}},
{
          "id":"2a67bb3ebf4d4284a536b14c40f4602c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":130,
              "y":498},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3e48254bc7d4a459eb9131794476d19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":130,
                  "y":498},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78633b68af594767bcb5ab9a7b442c3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"34px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF39611,
              "opacity":1},
            "location":{
              "x":129,
              "y":540},
            "size":{
              "width":58,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8296781ac2f400195451dd8d281a24e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"34px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF39611,
                  "opacity":1},
                "location":{
                  "x":129,
                  "y":540},
                "size":{
                  "width":58,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e0f67b2574447dca70f37ef7e2976a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF39611,
              "opacity":1},
            "location":{
              "x":189,
              "y":558},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e95a6e7d4475472ebfcbc4c014de402a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF39611,
                  "opacity":1},
                "location":{
                  "x":189,
                  "y":558},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b373f62de0e4e91b47dfbb5f887e87d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":44,
              "y":590},
            "size":{
              "width":286,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f7e37e0a17a4434b5e72d79751e150f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":44,
                  "y":590},
                "size":{
                  "width":286,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情状态模板/u303.png"}},
{
          "id":"8581a59075394a66a28bf90784546285",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":214,
              "y":558},
            "size":{
              "width":89,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2965eb6b1d304881930be564e9b48fb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":214,
                  "y":558},
                "size":{
                  "width":89,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"009742b35bbb428999fb6a07f7cf69e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":53,
              "y":600},
            "size":{
              "width":97,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16f74adb47954a688ace116660cb5ca6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":53,
                  "y":600},
                "size":{
                  "width":97,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a681cc6afa5241108953f361a51e1403",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":430},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bdd4e5cea1b4f848efd75dc05d3f3b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":430},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6268f21922ff4cc49c8d125de5a97e43",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":646},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bf0e8e507cf4fe0a024077c06ad3424",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":646},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8caa3c7b096540ef9a664bf8e0f14a5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":524},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"736aab81d392464fbbf8c75bbda0d354",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":524},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5d3ecaea4214376ba48c9d0a8d44e69",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":958},
            "size":{
              "width":320,
              "height":212},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebe25f901cb34c11b1e20353cb1525ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":958},
                "size":{
                  "width":320,
                  "height":212},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动详情（正在进行）/u60.png"}},
{
          "id":"e1e75e126611494d923c1a18bc4d221c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":936},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98755b6797f0498eb5d287a103394474",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":936},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b63cae6eb9b45aeae96a644cfa45fb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":974},
            "size":{
              "width":296,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d92b9de8a0f84e90b3e4d1a0212cb384",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":974},
                "size":{
                  "width":296,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c48c48ef23ee409bb7d8606e68268c5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":1138},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c24c8f1a8c34529be109af30bcb8d27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":1138},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9c52099f5e54a2fbf6c97e5c0268882",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":1140},
            "size":{
              "width":9,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b09918e74ac4ffea2e819cbb8e62b16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":1140},
                "size":{
                  "width":9,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u354.png"}},
{
          "id":"a626d5a756e345bc8267bbc9980ed735",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":1122},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/活动详情（正在进行）/u70_line.png"}},
{
          "id":"be2006762944405fa7ef799b158ebe19",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":886},
            "size":{
              "width":320,
              "height":39},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c80ce5b0539d4a8fb8b261e6c79ce3cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":886},
                "size":{
                  "width":320,
                  "height":39},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动详情（正在进行）/u83.png"}},
{
          "id":"3dba8fc527f44497929230e903d186d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":898},
            "size":{
              "width":287,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06c96d98e1ec445ea168e1e7ea94aca1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":898},
                "size":{
                  "width":287,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85fffc495d544e7698103edb99415dad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":305,
              "y":36},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7ac3abf1156438ba03bd9193f4f76f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":305,
                  "y":36},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b7a9d938b7b4185aef03c9e0a33a4e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":668},
            "size":{
              "width":320,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"522cad79a4d54961b30cafd20940daa3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":668},
                "size":{
                  "width":320,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情状态模板/u351.png"}},
{
          "id":"bf29109821b44155b7934f178acef445",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":674},
            "size":{
              "width":59,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb80eef1e524489f9e17b27d2df25455",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":674},
                "size":{
                  "width":59,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u616.png"}},
{
          "id":"5e3ba7912bbd44f99f33df353e4ce702",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":110,
              "y":684},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1ae8403d6d34230b73e0a9bc0fc462e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":110,
                  "y":684},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3ba44a93e6e49609843cd13f0e9ab4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":740},
            "size":{
              "width":320,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1344d6248e3e440c8688f46823b06149",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":740},
                "size":{
                  "width":320,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情状态模板/u351.png"}},
{
          "id":"d28616c4baee4d4e87d72db5821dbd6f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":748},
            "size":{
              "width":59,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b64eabd90184ce5aa90f70811301eba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":748},
                "size":{
                  "width":59,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u616.png"}},
{
          "id":"789ab08811dc44129aa057e19547f2f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":110,
              "y":756},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb62970b428c47daa0f5b0d8ad9b58dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":110,
                  "y":756},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ae1ef1de772460484aded3fe2a3d279",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":814},
            "size":{
              "width":320,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6d9bd5dc16743659d7245fcedfb12c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":814},
                "size":{
                  "width":320,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情状态模板/u351.png"}},
{
          "id":"8d9b858b4247483c9a2a02d6b2a5d2f3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":820},
            "size":{
              "width":59,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f364b571eda84a5a82a1ba8741557362",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":820},
                "size":{
                  "width":59,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u616.png"}},
{
          "id":"b4020f7d3ea04c9e8be9af784b8eaa7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":110,
              "y":830},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7aae7bac5f604d3c9ba152dd5882cf55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":110,
                  "y":830},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb73484117bb4745bac3b9e3b0a9195f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":21},
            "size":{
              "width":177,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"286b79e7ddb443438747fdc7ac17454d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":21},
                "size":{
                  "width":177,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动详情（秒杀中）/u120.png"}},
{
          "id":"0f4bf676c04140b5be67cf930ffceb49",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":302},
            "size":{
              "width":320,
              "height":110},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27cf28d673104adcbbb531ff13db63c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":302},
                "size":{
                  "width":320,
                  "height":110},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情状态模板/u6.png"}},
{
          "id":"4b4d834f51904dfb8710db6b4077fd46",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":282},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc75f788dd5f47598fe6f74835c1b585",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":282},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df516ce869ee488a99c0f0f54dd37bba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":324},
            "size":{
              "width":296,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"313b5736265542aea4bb93a53faf6900",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":324},
                "size":{
                  "width":296,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f9b67aeb2d945c89114288b5450a2f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":384},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac8f3469e00e4133b7fd22bafc865201",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":384},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bebeb8e25cd74b41aae3e2e4d2edd1a2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":104,
              "y":386},
            "size":{
              "width":9,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4095a91c23e04d8c9bca6fbccfd3732e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":104,
                  "y":386},
                "size":{
                  "width":9,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0元购/u354.png"}},
{
          "id":"655973e86f5c4b31bd327d03418749c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":704},
            "size":{
              "width":21,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02001c802e2f499e8a3d14da7025e216",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":704},
                "size":{
                  "width":21,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83e8d43b69654614953c9f22247c27cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":778},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9ef80cf86d84d3a8b56b36001c25976",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":778},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9abebc02b070455f9b08b7107bac5f30",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":850},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed78bad3ffb041beb2517da46bef7f7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":850},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"748db976d6d645d4af22f1b2f8372c59",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":756},
            "size":{
              "width":74,
              "height":32},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be88ed14baf848e88b6038ceecf4fddb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":249,
                  "y":756},
                "size":{
                  "width":74,
                  "height":32},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情状态模板/u409.png"}},
{
          "id":"1131aa08f8a74c108b3ac4c08988f8f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":688},
            "size":{
              "width":74,
              "height":32},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99988b9b47a34b2a84e7370adb2f5e11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":249,
                  "y":688},
                "size":{
                  "width":74,
                  "height":32},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情状态模板/u409.png"}},
{
          "id":"dba73678a47b46a98432e08bba81ae79",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":826},
            "size":{
              "width":74,
              "height":32},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76e7f48f80014fed97e195ed5b6c18ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":249,
                  "y":826},
                "size":{
                  "width":74,
                  "height":32},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情状态模板/u409.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "a8696e87bdc947a584e48d21c584a197":{
      "scriptId":"u0"},
    "d1c034539db647bd902cfcbef7cfc8fd":{
      "scriptId":"u1"},
    "b9089fb4ea5d469bb79055ffe6268eb3":{
      "scriptId":"u2"},
    "958657b42e894746bb1f2fe2eb64a9ca":{
      "scriptId":"u3"},
    "c0f47a67dc7649db95384bd645ae6044":{
      "scriptId":"u4"},
    "3943574302e4434180243242e16c6665":{
      "scriptId":"u5"},
    "8fe9ed1bdc3c4aa49f36fbaebcfb5200":{
      "scriptId":"u6"},
    "39c03a5d33c04cda98accd89a96fa3f7":{
      "scriptId":"u7"},
    "3714e784c72341acb7599107e0e32cf0":{
      "scriptId":"u8"},
    "8dc818cf78ea4158a59c2e14626ff3cb":{
      "scriptId":"u9"},
    "e87bb45e524b4e8da00ce293e4ac90cc":{
      "scriptId":"u10"},
    "dcbb085de4be49e1b2b749d09560db90":{
      "scriptId":"u11"},
    "c7265aff1e804c40989c507958065331":{
      "scriptId":"u12"},
    "b4e65dd3751e499e93b398e1a0364bfa":{
      "scriptId":"u13"},
    "d2201b73fd844ff69fd5e6824b601a6b":{
      "scriptId":"u14"},
    "6f29d6c3588e41bcbe90c03630de4969":{
      "scriptId":"u15"},
    "eccf1ef4c37149d5bf9f871ed8915708":{
      "scriptId":"u16"},
    "371daa7decbc4bf0935db392206dc726":{
      "scriptId":"u17"},
    "e32aa35455b7475297d8bfc13ad85e59":{
      "scriptId":"u18"},
    "039ea7124b7442989a62e62ff1030c47":{
      "scriptId":"u19"},
    "e6667ca28974413c9f6a4f0c7eaedbba":{
      "scriptId":"u20"},
    "2ec02e3f998346bfaf4dfd3fde8d0387":{
      "scriptId":"u21"},
    "70bfbba32f2d4ed3a7e730d84c55dec9":{
      "scriptId":"u22"},
    "fd13d6276f7746e9887e60cb3905c0ba":{
      "scriptId":"u23"},
    "a17238069ffe4dc08a6e3e817483cdf2":{
      "scriptId":"u24"},
    "63a97e890d844aaf80e1afd4796c7fbd":{
      "scriptId":"u25"},
    "183b7c5825f14f1db3f9bd603c2f41b2":{
      "scriptId":"u26"},
    "a4c7904d57c34a0cb61f7a3dffc2be2b":{
      "scriptId":"u27"},
    "b78ba9087e1c43c081c11b6eb0586945":{
      "scriptId":"u28"},
    "dfaa9d1275804b458a8916775b697778":{
      "scriptId":"u29"},
    "46a59231893e4f88b5ce341dd83500ae":{
      "scriptId":"u30"},
    "23b8733764f54904a3935e3f602068d1":{
      "scriptId":"u31"},
    "2a67bb3ebf4d4284a536b14c40f4602c":{
      "scriptId":"u32"},
    "b3e48254bc7d4a459eb9131794476d19":{
      "scriptId":"u33"},
    "78633b68af594767bcb5ab9a7b442c3b":{
      "scriptId":"u34"},
    "a8296781ac2f400195451dd8d281a24e":{
      "scriptId":"u35"},
    "7e0f67b2574447dca70f37ef7e2976a6":{
      "scriptId":"u36"},
    "e95a6e7d4475472ebfcbc4c014de402a":{
      "scriptId":"u37"},
    "6b373f62de0e4e91b47dfbb5f887e87d":{
      "scriptId":"u38"},
    "4f7e37e0a17a4434b5e72d79751e150f":{
      "scriptId":"u39"},
    "8581a59075394a66a28bf90784546285":{
      "scriptId":"u40"},
    "2965eb6b1d304881930be564e9b48fb7":{
      "scriptId":"u41"},
    "009742b35bbb428999fb6a07f7cf69e9":{
      "scriptId":"u42"},
    "16f74adb47954a688ace116660cb5ca6":{
      "scriptId":"u43"},
    "a681cc6afa5241108953f361a51e1403":{
      "scriptId":"u44"},
    "6bdd4e5cea1b4f848efd75dc05d3f3b6":{
      "scriptId":"u45"},
    "6268f21922ff4cc49c8d125de5a97e43":{
      "scriptId":"u46"},
    "3bf0e8e507cf4fe0a024077c06ad3424":{
      "scriptId":"u47"},
    "8caa3c7b096540ef9a664bf8e0f14a5d":{
      "scriptId":"u48"},
    "736aab81d392464fbbf8c75bbda0d354":{
      "scriptId":"u49"},
    "a5d3ecaea4214376ba48c9d0a8d44e69":{
      "scriptId":"u50"},
    "ebe25f901cb34c11b1e20353cb1525ef":{
      "scriptId":"u51"},
    "e1e75e126611494d923c1a18bc4d221c":{
      "scriptId":"u52"},
    "98755b6797f0498eb5d287a103394474":{
      "scriptId":"u53"},
    "7b63cae6eb9b45aeae96a644cfa45fb2":{
      "scriptId":"u54"},
    "d92b9de8a0f84e90b3e4d1a0212cb384":{
      "scriptId":"u55"},
    "c48c48ef23ee409bb7d8606e68268c5c":{
      "scriptId":"u56"},
    "2c24c8f1a8c34529be109af30bcb8d27":{
      "scriptId":"u57"},
    "d9c52099f5e54a2fbf6c97e5c0268882":{
      "scriptId":"u58"},
    "2b09918e74ac4ffea2e819cbb8e62b16":{
      "scriptId":"u59"},
    "a626d5a756e345bc8267bbc9980ed735":{
      "scriptId":"u60"},
    "be2006762944405fa7ef799b158ebe19":{
      "scriptId":"u61"},
    "c80ce5b0539d4a8fb8b261e6c79ce3cb":{
      "scriptId":"u62"},
    "3dba8fc527f44497929230e903d186d7":{
      "scriptId":"u63"},
    "06c96d98e1ec445ea168e1e7ea94aca1":{
      "scriptId":"u64"},
    "85fffc495d544e7698103edb99415dad":{
      "scriptId":"u65"},
    "e7ac3abf1156438ba03bd9193f4f76f9":{
      "scriptId":"u66"},
    "5b7a9d938b7b4185aef03c9e0a33a4e7":{
      "scriptId":"u67"},
    "522cad79a4d54961b30cafd20940daa3":{
      "scriptId":"u68"},
    "bf29109821b44155b7934f178acef445":{
      "scriptId":"u69"},
    "bb80eef1e524489f9e17b27d2df25455":{
      "scriptId":"u70"},
    "5e3ba7912bbd44f99f33df353e4ce702":{
      "scriptId":"u71"},
    "f1ae8403d6d34230b73e0a9bc0fc462e":{
      "scriptId":"u72"},
    "b3ba44a93e6e49609843cd13f0e9ab4c":{
      "scriptId":"u73"},
    "1344d6248e3e440c8688f46823b06149":{
      "scriptId":"u74"},
    "d28616c4baee4d4e87d72db5821dbd6f":{
      "scriptId":"u75"},
    "0b64eabd90184ce5aa90f70811301eba":{
      "scriptId":"u76"},
    "789ab08811dc44129aa057e19547f2f1":{
      "scriptId":"u77"},
    "bb62970b428c47daa0f5b0d8ad9b58dc":{
      "scriptId":"u78"},
    "1ae1ef1de772460484aded3fe2a3d279":{
      "scriptId":"u79"},
    "e6d9bd5dc16743659d7245fcedfb12c0":{
      "scriptId":"u80"},
    "8d9b858b4247483c9a2a02d6b2a5d2f3":{
      "scriptId":"u81"},
    "f364b571eda84a5a82a1ba8741557362":{
      "scriptId":"u82"},
    "b4020f7d3ea04c9e8be9af784b8eaa7d":{
      "scriptId":"u83"},
    "7aae7bac5f604d3c9ba152dd5882cf55":{
      "scriptId":"u84"},
    "cb73484117bb4745bac3b9e3b0a9195f":{
      "scriptId":"u85"},
    "286b79e7ddb443438747fdc7ac17454d":{
      "scriptId":"u86"},
    "0f4bf676c04140b5be67cf930ffceb49":{
      "scriptId":"u87"},
    "27cf28d673104adcbbb531ff13db63c4":{
      "scriptId":"u88"},
    "4b4d834f51904dfb8710db6b4077fd46":{
      "scriptId":"u89"},
    "fc75f788dd5f47598fe6f74835c1b585":{
      "scriptId":"u90"},
    "df516ce869ee488a99c0f0f54dd37bba":{
      "scriptId":"u91"},
    "313b5736265542aea4bb93a53faf6900":{
      "scriptId":"u92"},
    "4f9b67aeb2d945c89114288b5450a2f8":{
      "scriptId":"u93"},
    "ac8f3469e00e4133b7fd22bafc865201":{
      "scriptId":"u94"},
    "bebeb8e25cd74b41aae3e2e4d2edd1a2":{
      "scriptId":"u95"},
    "4095a91c23e04d8c9bca6fbccfd3732e":{
      "scriptId":"u96"},
    "655973e86f5c4b31bd327d03418749c9":{
      "scriptId":"u97"},
    "02001c802e2f499e8a3d14da7025e216":{
      "scriptId":"u98"},
    "83e8d43b69654614953c9f22247c27cd":{
      "scriptId":"u99"},
    "e9ef80cf86d84d3a8b56b36001c25976":{
      "scriptId":"u100"},
    "9abebc02b070455f9b08b7107bac5f30":{
      "scriptId":"u101"},
    "ed78bad3ffb041beb2517da46bef7f7f":{
      "scriptId":"u102"},
    "748db976d6d645d4af22f1b2f8372c59":{
      "scriptId":"u103"},
    "be88ed14baf848e88b6038ceecf4fddb":{
      "scriptId":"u104"},
    "1131aa08f8a74c108b3ac4c08988f8f5":{
      "scriptId":"u105"},
    "99988b9b47a34b2a84e7370adb2f5e11":{
      "scriptId":"u106"},
    "dba73678a47b46a98432e08bba81ae79":{
      "scriptId":"u107"},
    "76e7f48f80014fed97e195ed5b6c18ab":{
      "scriptId":"u108"}}});